import {
    FileImage,
    FileMinus,
    FilePlus,
    Image as ImageIcon,
    Key,
    LockOpen,
    Merge,
    RotateCw,
    Scissors,
    Smartphone,
    Repeat,
    Minimize2,
    Maximize,
    Crop,
    FileSpreadsheet,
    Database,
    Table2,
    FileText,
    CodeXml,
    Code,
    Terminal,
    FileCode,
    FileDown,
    Globe
} from "lucide-react";

export const TOOLS = [
    // PDF Utilities
    {
        id: "merge-pdf",
        title: "Merge PDF",
        description: "Combine multiple PDF files into one.",
        href: "/tools/merge-pdf",
        icon: Merge,
    },
    {
        id: "split-pdf",
        title: "Split PDF",
        description: "Separate one page or a whole set for easy conversion.",
        href: "/tools/split-pdf",
        icon: Scissors,
    },
    {
        id: "compress-pdf",
        title: "Compress PDF",
        description: "Reduce file size while saving quality.",
        href: "/tools/compress-pdf",
        icon: FileMinus,
    },
    {
        id: "rotate-pdf",
        title: "Rotate PDF",
        description: "Rotate your PDFs the way you need them.",
        href: "/tools/rotate-pdf",
        icon: RotateCw,
    },
    {
        id: "add-watermark",
        title: "Add Watermark",
        description: "Stamp an image or text over your PDF in seconds.",
        href: "/tools/add-watermark",
        icon: FilePlus,
    },
    {
        id: "protect-pdf",
        title: "Protect PDF",
        description: "Encrypt your PDF with a password.",
        href: "/tools/protect-pdf",
        icon: Key,
    },
    {
        id: "unlock-pdf",
        title: "Unlock PDF",
        description: "Remove PDF password security.",
        href: "/tools/unlock-pdf",
        icon: LockOpen,
    },
    // Image Utilities
    {
        id: "image-to-pdf",
        title: "Image to PDF",
        description: "Convert JPG, PNG, and WebP to PDF.",
        href: "/tools/image-to-pdf",
        icon: FileImage,
    },
    {
        id: "pdf-to-image",
        title: "PDF to Image",
        description: "Extract images from PDF or convert pages to images.",
        href: "/tools/pdf-to-image",
        icon: ImageIcon,
    },
    {
        id: "heic-to-jpg",
        title: "HEIC to JPG",
        description: "Convert Apple HEIC images to standard JPEGs.",
        href: "/tools/heic-to-jpg",
        icon: Smartphone,
    },
    {
        id: "webp-converter",
        title: "WebP Converter",
        description: "Convert WebP images into standard PNG or JPG files.",
        href: "/tools/webp-converter",
        icon: Repeat,
    },
    {
        id: "compress-image",
        title: "Compress Image",
        description: "Reduce the file size of your images via JPEG compression locally.",
        href: "/tools/compress-image",
        icon: Minimize2,
    },
    {
        id: "resize-image",
        title: "Resize Image",
        description: "Change the dimensions of your image precisely.",
        href: "/tools/resize-image",
        icon: Maximize,
    },
    {
        id: "crop-image",
        title: "Crop Image",
        description: "Visually trim the edges off your image.",
        href: "/tools/crop-image",
        icon: Crop,
    },
    // Office & Data Utilities
    {
        id: "excel-to-csv",
        title: "Excel to CSV",
        description: "Extract the primary spreadsheet of an Excel file into a raw CSV.",
        href: "/tools/excel-to-csv",
        icon: FileSpreadsheet,
    },
    {
        id: "excel-to-json",
        title: "Excel to JSON",
        description: "Convert grid data rows from an Excel file into a JSON document.",
        href: "/tools/excel-to-json",
        icon: Database,
    },
    {
        id: "csv-to-excel",
        title: "CSV to Excel",
        description: "Convert messy CSV data blocks safely into modern Excel (.xlsx).",
        href: "/tools/csv-to-excel",
        icon: Table2,
    },
    {
        id: "docx-to-txt",
        title: "DOCX to TXT",
        description: "Pull the raw semantic text content cleanly out of Microsoft Word documents.",
        href: "/tools/docx-to-txt",
        icon: FileText,
    },
    {
        id: "docx-to-html",
        title: "DOCX to HTML",
        description: "Convert heavy Word formatting into semantic Web HTML5 markup.",
        href: "/tools/docx-to-html",
        icon: CodeXml,
    },
    // Developer & Data Science Utilities
    {
        id: "code-to-pdf",
        title: "Code to PDF",
        description: "Export beautifully formatted code specifically wrapped for A4 PDF documentation natively.",
        href: "/tools/code-to-pdf",
        icon: Code,
    },
    {
        id: "code-to-image",
        title: "Code snippet to Image",
        description: "Generate beautiful, crisp syntax-highlighted pictures of your code.",
        href: "/tools/code-to-image",
        icon: Terminal,
    },
    {
        id: "ipynb-to-pdf",
        title: "IPYNB to PDF",
        description: "Completely export your Notebooks into clean documents.",
        href: "/tools/ipynb-to-pdf",
        icon: FileText,
    },
    {
        id: "ipynb-to-html",
        title: "IPYNB to HTML",
        description: "Export Jupyter notebooks into beautifully styled offline webpages.",
        href: "/tools/ipynb-to-html",
        icon: Globe,
    },
    {
        id: "ipynb-to-md",
        title: "IPYNB to Markdown",
        description: "Wrap code cells and extract structural text directly into Markdown formatting.",
        href: "/tools/ipynb-to-md",
        icon: FileDown,
    },
    {
        id: "ipynb-to-py",
        title: "IPYNB to Python",
        description: "Unpack Notebooks and extract a clean, raw `.py` script.",
        href: "/tools/ipynb-to-py",
        icon: FileCode,
    },
    {
        id: "merge-ipynb",
        title: "Merge Notebooks",
        description: "Combine multiple `.ipynb` notebooks into one single master notebook instantly.",
        href: "/tools/merge-ipynb",
        icon: Merge,
    },
];
